#!/usr/bin/env node
// Turns the repository's ABIs, deployment addresses and evidence files into typed modules under
// src/generated, so the app builds on its own (for example on Vercel with app/ as the root).
// Run from app/: npm run sync. The generated files are committed.
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const app = join(dirname(fileURLToPath(import.meta.url)), '..')
const repo = join(app, '..')
const out = join(app, 'src', 'generated')
const header = '// Generated by scripts/sync.mjs. Do not edit.\n'

const abis = {
  lensAbi: 'StockReefLens',
  marketAbi: 'StockReefMarket',
  escrowAbi: 'RepaymentEscrow',
  gateAbi: 'PriceGate',
  demoAbi: 'DemoController',
  policyAbi: 'SessionRiskPolicy',
  erc20Abi: 'MockUSDG',
}
let abiTs = header
for (const [name, file] of Object.entries(abis)) {
  const abi = readFileSync(join(repo, 'abi', `${file}.json`), 'utf8').trim()
  abiTs += `export const ${name} = ${abi} as const\n`
}
writeFileSync(join(out, 'abi.ts'), abiTs)

const deployments = {}
for (const f of readdirSync(join(repo, 'deployments'))) {
  const m = f.match(/^addresses\.(\d+)\.json$/)
  if (!m) continue
  deployments[m[1]] = JSON.parse(readFileSync(join(repo, 'deployments', f), 'utf8'))
  // The first deployment block, from the deployment evidence, so the app reads logs from there and no earlier.
  const evidenceFile = join(repo, 'evidence', `deploy-${m[1]}.json`)
  if (existsSync(evidenceFile)) {
    const blocks = (JSON.parse(readFileSync(evidenceFile, 'utf8')).transactions ?? []).map(t => t.blockNumber).filter(Number.isInteger)
    if (blocks.length) deployments[m[1]].deployBlock = Math.min(...blocks)
  }
}
writeFileSync(join(out, 'deployments.ts'), `${header}export const deployments: Record<string, Record<string, string | number>> = ${JSON.stringify(deployments, null, 1)}\n`)

const evidence = { golden: JSON.parse(readFileSync(join(repo, 'tools', 'golden', 'golden.json'), 'utf8')), runs: {} }
const evDir = join(repo, 'evidence')
if (existsSync(evDir)) {
  for (const f of readdirSync(evDir)) {
    if (f.endsWith('.json')) evidence.runs[f.replace(/\.json$/, '')] = JSON.parse(readFileSync(join(evDir, f), 'utf8'))
  }
}
writeFileSync(join(out, 'evidence.ts'), `${header}export const evidence = ${JSON.stringify(evidence, null, 1)} as const\n`)
console.log(`synced ${Object.keys(abis).length} ABIs, deployments for ${Object.keys(deployments).join(', ') || 'none'}, ${Object.keys(evidence.runs).length} evidence files`)
